title: Cristiam Espinoza
description: My Personal Geek Blog
author: Cristiam Espinoza
logo: /static/img/avatar.png
github: https://github.com/cristiam-espinoza
about: Freelance developer

baseurl: "http://cespinoza.me"
url: "http://cespinoza.me"

allowsearch: true

disqus_shortname: cespinoza
google_analytics: UA-72862926-1

share:
  twitter_username: \#DevOps_Latam
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
